### ISSUE TITLE
Profile and optimize culledPairs

### ISSUE THREAD

**Issue by schell** [ublubu/shapes#1]
I'm guessing you already knew this as you mention in first in your [reddit link](https://www.reddit.com/r/haskell/comments/4ci8uu/shapes_optimizing_a_2d_physics_engine/) but just doing a quick `stack build --executable-profiling --library-profiling --ghc-options="-fprof-auto"` shows that `Physics.Broadphase.Opt.Aabb.culledPairs.f` is the biggest CPU cost center. It has two IntMap lookups which at first I thought may be the culprit but IM.lookup doesn't even show up in the prof file, and I've enabled library profiling. I'm not sure - I'd like to take a look at the generated core and see if I can make any sense of it. It could be that using a list is the culprit.

<img width="1259" alt="screenshot 2016-03-29 23 14 05" src="https://cloud.githubusercontent.com/assets/24942/14133592/570196ce-f605-11e5-9012-9b8a06dcaa72.png">

**Comment by schell** [comment]
Also - `drawLine` is obviously a bottleneck as well (after adding an inline statement on toRenderable) - but at first glance it looks like it mostly proxies to `sdl2.drawLine`.

<img width="279" alt="screenshot 2016-03-29 23 27 12" src="https://cloud.githubusercontent.com/assets/24942/14133661/08665ef4-f606-11e5-80e1-57126945af3e.png">

**Comment by ublubu** [comment]
Oh yes, the drawing code is quite slow, but I'm only interested in the performance of the engine itself. The demo is really just for debugging and showing to people.

As for the cost centers, I haven't seen functions from other libraries in my .prof files. I've asked around before, but I haven't heard the answer yet. I can only guess that I'm missing a flag somewhere that I don't know about.

**Comment by ublubu** [comment]
Also, yes please have a look at the core. Let me know how that goes. I've never done it before, but I'll probably have to start soon.

**Comment by schell** [comment]
Okay - it seems that you can't profile "remote" libraries...which seems backwards. Maybe it's just a limitation of stack? Anyway - I got around this by including `containers` locally and referencing my local copy in the stack.yaml. After that it's pretty clear that IM.lookup is the culprit.

<img width="669" alt="screenshot 2016-03-30 16 03 06" src="https://cloud.githubusercontent.com/assets/24942/14160419/20d3824c-f691-11e5-8126-39241fcc76fc.png">

**Comment by ublubu** [comment]
Hey, that's really exciting. The broadphase culling doesn't cache anything between frames or between solver steps, so it should be pretty simple to try something mutable and/or parallel in just the `Aabb` module.

Btw, if you run a `Main` with just [this line](https://github.com/ublubu/shapes/blob/62307568c0851c8d936bb067e3f8e0d74752bef8/shapes/src/Main.hs#L25), you can profile just running the engine itself a fixed number of frames.

How do you include libraries locally? Is that where you manually `cabal install ../containers-src-blah` a package from source?

**Comment by schell** [comment]
Yeah - I `git clone`d the containers library and then specified the path to the directory using the stack.yaml file.

<img width="218" alt="screenshot 2016-03-30 20 46 44" src="https://cloud.githubusercontent.com/assets/24942/14164896/8fc4d008-f6b8-11e5-873a-d63aab60a3ed.png">

**Comment by ublubu** [comment]
dd06d891f6d06b2b37182751c9c1768aa2ff5b10 It's a lot quicker now.

I'm also trying out repa a little.

**Comment by schell** [comment]
That's great! I'm also in the process of porting all my use of lists to unboxed vectors for my graphics library. Let's hope I see similar results.

:+1:

**Comment by ublubu** [comment]
It turns out IntMap performs about the same as a mutable Data.HashTable.ST.Basic for my usage.

I moved some things around so I could use unboxed vectors for my caching and got ~2x speed improvement for 225 boxes. I also put INLINE pragmas on a bunch of things so performance is more predictable with code changes.

**Comment by schell** [comment]
How are you measuring your speed increase? I'm guessing you're logging the delta each frame - I ask because I'm profiling my code and would like to know/use your method. Have you used Criterion?

**Comment by ublubu** [comment]
I've been relying criterion almost exclusively. I've haven't found profiling to be as useful, especially now that I'm inlining so much. Profiling also affected the runtime characteristics of some pieces of code that I tested.

I have an [executable section](https://github.com/ublubu/shapes/blob/816afd35f2dfa89368d63c9223b0a2c0e52dbdab/shapes/shapes.cabal#L135) of my cabal file that I use. I should probably move the benchmarking stuff to a separate root dir so I can add `shapes` as a dependency (as I've done with the test section).

**Comment by ublubu** [comment]
going to close this one. the sparse-grid broadphase seems to work very well.
