### ISSUE TITLE
Quick question on status

### ISSUE THREAD

**Issue by schell** [ublubu/shapes#16]
Hey there @ublubu! Are you still working on this project? Any idea how long before a hackage release (0.1 even).

**Comment by ublubu** [comment]
Hi! I've been busy interviewing and moving to New York. I'll get back to `shapes` soon, since it's my highest-priority hobby project. I haven't put much thought into releasing it, but I can aim for some kind of initial release in September. Are you interested in using it for something?

**Comment by schell** [comment]
Awesome! Congrats on the move. Yes, I am interested in using it for my game https://github.com/schell/odin. It's not imperative that you release it, I can pull from github until then, but I did want to check and make sure it's not vaporware, because I don't think I would have the bandwidth to keep supporting it in your absence. Thanks again - great project!

**Comment by ublubu** [comment]
Hey, that's great to hear! I'll definitely hop back on it, then. Go ahead and make issues for whatever features/improvements you want.

Is there a good issue/work tracker I can connect to GitHub (or another version control thing) so we can both keep track of what I'm working on?

**Comment by schell** [comment]
Great! I can't wait to integrate shapes :) 
I can easily enough check out your work through github issues. The only immediate want I have is maybe some initial hookup tutorial in the wiki to make onboarding a bit easier, but until then I can hack around myself :) Thanks again.
