### ISSUE TITLE
What is meant by mass as a vector?

### ISSUE THREAD

**Issue by schell** [ublubu/shapes#17]
In `Physics.Engine.Class`, `makePhysicalObj` takes a mass of (x, y). Why is the mass a vector? What does it represent?

https://github.com/ublubu/shapes/blob/master/shapes/src/Physics/Engine/Class.hs#L23

**Comment by ublubu** [comment]
Always good to get ideas for what should go in the guide.

https://github.com/ublubu/shapes/blob/ee472b72ed812fa0d921e3031172894dc529938b/shapes/src/Physics/Constraint.hs#L30

Not the best names, but the second one is actually rotational inertia.

**Comment by schell** [comment]
Okay - and so `toInvMass2` takes a linear mass and a rotational mass?

**Comment by ublubu** [comment]
yes
