### ISSUE TITLE
Consider using the Linear library

### ISSUE THREAD

**Issue by tysonzero** [ublubu/shapes#76]
The [linear](http://hackage.haskell.org/package/linear) library seems to provide a very nice interface and lots of useful typeclasses for lienar algebra. I know we are personally using it for our game. This library would be noticeably nicer to use if it used the types from there rather than re-implementing them.

There may of course be good reasons why you are not using that library, but I figured it was worth mentioning and asking about.

**Comment by schell** [comment]
As far as I know @ublubu switched from `linear` early on because of performance reasons. I think it was faster to use monomorphised, unboxed numeric types and specialize everything. You may be able to find some details going through previous commits.

**Comment by tysonzero** [comment]
@schell Ah dang, I was worried that would be the case, I wonder if there is anything that can be done to speedup the Linear library instead.

**Comment by schell** [comment]
Oooooor look into [this linear killer](https://github.com/waivio/cl3). I know this is a different direction, but I just discovered geometric algebra. 

AFAIK linear's performance is due to the high level of abstraction in its types. Kynan (@ublubu) can speak more to that, though.

**Comment by tysonzero** [comment]
@schell Isn't that library aimed at 3 dimensional space?

And ah ok yeah lets see what @ublubu has to say, I think what you said is probably true.

**Comment by schell** [comment]
Yeah, it is but you can still use it, just set z constant. It's an interesting concept, anyway.

**Comment by ublubu** [comment]
Whoops. I have not been paying attention.

Yeah, the stuff @schell said is right afaict.

I'm excited to learn about geometric algebra. Looks like `cl3` is plenty fast. Maybe there are ideas to steal, even if I don't use the library itself.
